Remove ReactAIContainer
anastasiia-zolochevska/react-appinsights pull request #54
Opened 2019-03-07 15:52 UTC by pviotti

ReactAIContainer is a singleton object that contains an instance of ReactAI and an instance of AppInsights to expose to the withAITracking function.  
I think we can avoid using it by exposing the AppInsights as a static variable of ReactAI.

This PR also 
- updates dependencies
- removes jest-environment-node-debug (because it's [not actively maintained](https://github.com/NikhilVerma/jest-environment-node-debug-fixed) - and anyway there are [better ways](https://github.com/Microsoft/vscode-recipes/tree/master/debugging-jest-tests) of debugging jest tests..)
- fixes a circular dependency warning upon build
- adds a VS Code launch file to debug jest tests
- simplifies tests

2019-03-07 21:08 UTC, hiraldesai requested changes

2019-03-07 21:08 UTC, hiraldesai commented on test/ReactAI.test.ts
> -    expect(reactAI._aiInternal.trackPageView).toHaveBeenNthCalledWith(2, pageViewTelemetry3);
Can we call _aiInternal either “ai” or “appInsights”?

2019-03-07 21:08 UTC, hiraldesai commented on src/withAITracking.tsx
> -      if (!container || !ai) {
Is this cast necessary here?

2019-03-08 09:25 UTC, pviotti commented on src/withAITracking.tsx
> -      if (!container || !ai) {
no it's not: good catch, thanks

2019-03-08 09:26 UTC, pviotti commented on test/ReactAI.test.ts
> -    expect(reactAI._aiInternal.trackPageView).toHaveBeenNthCalledWith(2, pageViewTelemetry3);
ok

2019-03-08 09:31 UTC, merged